/*
 * File generated by Test generator (dotup.dotup-vscode-test-generator)
 * Date: 2021-10-11 03:29:04
*/
import { DefaultLabelModel } from '../../src/label/DefaultLabelModel';
import { DiagramEngine, LabelModel, LabelModelGenerics, LabelModelOptions } from "@projectstorm/react-diagrams-core";
import { DeserializeEvent } from "@projectstorm/react-canvas-core";

describe('Test class DefaultLabelModel', () => {

it('DefaultLabelModel-setLabel', () => {
// Arguments
const options1 = undefined;
const label1 = 'Oha';

// Method call
const defaultLabelModel = new DefaultLabelModel(options1);
 defaultLabelModel.setLabel(label1);
});

it('DefaultLabelModel-deserialize', () => {
// Arguments
const options2 = undefined;
const event1 = undefined;

// Method call
const defaultLabelModel = new DefaultLabelModel(options2);
 defaultLabelModel.deserialize(event1);
});

it('DefaultLabelModel-serialize', () => {
// Arguments
const options3 = undefined;

// Method call
const defaultLabelModel = new DefaultLabelModel(options3);
 defaultLabelModel.serialize();
});

});
